version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=fincashly;Username=postgres;Password=postgres

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fincashly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"